version: "3"

services:
  nlp-experiments:
    build: .
    image: nlp-experiments
    #image: tensorflow/tensorflow:latest-gpu-jupyter
    container_name: nlp-experiments
    working_dir: /nlp
    ports:
      - 443:443
      - 8888:8888
      - 6006:6006
    command: jupyter lab --config=/root/.jupyter/jupyter_lab_config.py
    volumes:
      - "$HOME/git/nlp-experiments/src:/nlp"
      - "$HOME/git/nlp-experiments/jupyter_lab_config.py:/root/.jupyter/jupyter_lab_config.py"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
